// <auto-generated />
namespace PrsServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removereqfromphoneandemail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removereqfromphoneandemail));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281458387_remove req from phone and email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
